# Busybox

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-pod
  labels:
    chart:version
spec:
  selector:
    matchLabels:
      app: busybox
  replicas: 2 
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: myapp-container
        image: busybox
      initContainers:
      - name: init-myservice
        image: busybox
        command: ['sh', '-c', "sleep 2"]
        
